site_name: Quan's Game Development Toolbox
site_author: Quan Hoang

nav:
  - ğŸ  Home: index.md

  - ğŸ“– About:
      - Overview: about.md
      - License: license.md
      - Release Notes: release-notes.md

  - ğŸ§­ Getting Started:
      - User Guide: guide.md
      - Project Structure: structure.md
      - Contributing: contributing.md

  - ğŸ§° Toolbox:
      - By Engine:
          - Godot (4.6):
              - Scripts:
                  -2D Top-down Movement: engines/godot/scripts/top-down-movement.md
                  -2D Platformer Movement: engines/godot/scripts/2d-platformer-movement.md
                  -2D Sideview Scene-Based Building: engines/godot/scripts/side-view-building.md
                  -Level Change System: engines/godot/scripts/level-change.md
                  -2D Pick-upable Item That Hovers: engines/godot/scripts/2d-hover-pick-up-item.md
      - By System:
          - Player Movement: systems/player_movement.md
          - Combat: systems/combat.md
          - UI & UX: systems/ui.md
          - AI & Behavior: systems/ai.md
      - By Project:
          - Project Index: projects/index.md

  - ğŸ§ª Experiments:
      - Prototypes: experiments/prototypes.md
      - Highly Game Specific Mechanics:
          - Ghost: experiments/specific/ghost.md

  - ğŸ“ References:
      - Resources: references/resources.md
      - Credits & Inspirations: references/credits.md

theme:
  name: dracula
  favicon: assets/favicon.ico
